rooms:
  всекидневна:
    devices:
      сензор:
        type: temperature
        url: http://192.168.0.103/sensor
        methods:
          GET:
            temperature: /temperature

  спалня:
    devices:
      лампа:
        type: relay
        url: http://192.168.0.101/relay
        methods:
          GET: 
            state: /state
          POST:
            on:
              state: "on"
            off:
              state: "off"
      сензор:
        type: climate
        url: http://192.168.0.102/sensor
        methods:
          GET:
            temperature: /temperature
            humidity: /humidity
            all: /
